[package]
name = "stellar-json-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
soroban-client = "0.3.7"
stellar-baselib = "0.4.6"
tokio = { version = "1.35.1", features = ["full"] }
base64 = "0.22.1"

serde = "1.0.217"
bincode = "1.3.3"
